[project]
authors = ["Antonio Camargo <antoniop.camargo@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "msa-guided-structure-superposition"
platforms = ["linux-64", "osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
biopython = ">=1.85,<2"
python = ">=3.13.2,<3.14"
rich = ">=13.9.4,<14"
rich-click = ">=1.8.8,<2"
